name: CI

on:
  push:
  pull_request:

jobs:
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Package exe
      run: |
        pyinstaller -F --noconsole .\enhance_export_gui.py
    - name: Upload exe
      uses: actions/upload-artifact@v3
      with:
        name: enhance_export_gui
        path: dist/enhance_export_gui.exe
