name: Handle Release
on:
  release:
    types: [created]

jobs:
  generate:
    name: Create release-artifacts
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Package exe
        run: |
          pyinstaller -F --noconsole .\enhance_export_gui.py
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'dist/*.exe'
